### ISSUE TITLE
Test Answers No Longer Available

### ISSUE THREAD

**Issue by ShadowFox88** [Klivess/AutomaticSmartRevise#1]
Due to the (not very) recent change with the way discord hosts files, the link in the source code at [Line 53 on bot.cs](https://github.com/Klivess/AutomaticSmartRevise/blob/master/AutomaticSmartRevise/bot.cs#L53) does not resolve anymore.

**Comment by Klivess** [comment]
Fixed the link [in the newest release](https://github.com/Klivess/AutomaticSmartRevise/releases/tag/release1.0.2), thanks for letting me know.

**Comment by ShadowFox88** [comment]
Doesn't seem to have fixed the issue - still shows "This content is no longer available"
![](https://cdn.vahin.dev/u/ddd06342-1aee-4b6b-90e2-ee1b323028de.png)

**Comment by Klivess** [comment]
Should actually work now, I mis-tested it last time

Let me know if it still doesn't work [release1.0.3](https://github.com/Klivess/AutomaticSmartRevise/releases/tag/release1.0.3)
